-- MySQL Script generated by MySQL Workbench
-- Sat Jan 29 15:31:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `base` ;

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base` DEFAULT CHARACTER SET utf8 ;
USE `base` ;

-- -----------------------------------------------------
-- Table `base`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `base`.`contacts` ;

CREATE TABLE IF NOT EXISTS `base`.`contacts` (
  `contact_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `contact_Nom` VARCHAR(128) NOT NULL,
  `contact_Prenom` VARCHAR(256) NOT NULL,
  `contact_Mail` TEXT NOT NULL,
  `contact_Titre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`contact_ID`),
  UNIQUE INDEX `contact_ID_UNIQUE` (`contact_ID` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `base`.`contacts`
-- -----------------------------------------------------
START TRANSACTION;
USE `base`;
INSERT INTO `base`.`contacts` (`contact_ID`, `contact_Nom`, `contact_Prenom`, `contact_Mail`, `contact_Titre`) VALUES (1, 'EXAMPLE', 'One', 'one.example@fai.com', 'Responsable du Master 1');
INSERT INTO `base`.`contacts` (`contact_ID`, `contact_Nom`, `contact_Prenom`, `contact_Mail`, `contact_Titre`) VALUES (2, 'EXAMPLE', 'Two', 'two.ewample@fai.com', 'Responsable du diplôme');

COMMIT;

